modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"

[[mods]]
modId="suggestion_tweaker"
version="${version}"
displayName="Suggestion Tweaker"
authors="VelizarBG"
description='''
Improves the way suggestions are filtered when writing a command
'''
logoFile = "icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker"
issueTrackerURL = "https://github.com/VelizarBG/suggestion-tweaker/issues"

[[dependencies.suggestion_tweaker]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.suggestion_tweaker]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
